name: Reaper - Run Dev
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
#   schedule:
#     - cron: '*/5 * * * *' # Every 5 minutes
  workflow_dispatch:

jobs:
  run-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reaper/requirements.txt
      - name: Run Reaper
        run: |
          python reaper/reaper.py --subscription-id '${{ secrets.AZURE_SUBSCRIPTION_ID }}' --resource-group '${{ vars.AZURE_RESOURCE_GROUP }}' --registry-name '${{ vars.AZURE_REGISTRY_NAME }}'
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      